"""add password to citizen

Revision ID: 6c916f94e943
Revises: ec0520f17139
Create Date: 2019-05-10 17:19:03.456095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c916f94e943'
down_revision = 'ec0520f17139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admin_name', table_name='admin')
    op.drop_index('ix_admin_permission', table_name='admin')
    op.drop_table('admin')
    op.add_column('citizen', sa.Column('score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citizen', 'score')
    op.create_table('admin',
    sa.Column('admin_id', sa.VARCHAR(length=12), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('permission', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_index('ix_admin_permission', 'admin', ['permission'], unique=False)
    op.create_index('ix_admin_name', 'admin', ['name'], unique=False)
    # ### end Alembic commands ###
