"""reports

Revision ID: 75da740a16e4
Revises: 7e5ab9b6cad8
Create Date: 2019-05-01 20:45:55.687956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75da740a16e4'
down_revision = '7e5ab9b6cad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('reporter_id', sa.String(length=12), nullable=True),
    sa.Column('reported_id', sa.String(length=12), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('report_category', sa.String(length=64), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['reported_id'], ['citizen.citizen_id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['citizen.citizen_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_report_time'), 'report', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_time'), table_name='report')
    op.drop_table('report')
    # ### end Alembic commands ###
