"""citizens

Revision ID: 7e5ab9b6cad8
Revises: 
Create Date: 2019-05-01 17:09:54.046758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e5ab9b6cad8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citizen',
    sa.Column('citizen_id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('citizen_id')
    )
    op.create_index(op.f('ix_citizen_name'), 'citizen', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citizen_name'), table_name='citizen')
    op.drop_table('citizen')
    # ### end Alembic commands ###
